language: minimal
services:
    - docker

before_deploy:
    - docker build . -t docker.pkg.github.com/tooxo/website-mainpage/mainpage
    - docker build . -t tooxo/website-mainpage:mainpage
    - docker build Spotify2Mp3/ -t docker.pkg.github.com/tooxo/website-mainpage/spotify2mp3
    - docker build Spotify2Mp3/ -t tooxo/website-mainpage:spotify2mp3

deploy:
    # Deploy MainPage to GitHub
    -   provider: script
        script: bash -c "echo '"$GITHUB_KEY" | docker login docker.pkg.github.com --username "$GITHUB_USERNAME" --password-stdin; docker push docker.pkg.github.com/tooxo/website-mainpage/mainpage'
    # Deploy MainPage to DockerHub
    -   provider: script
        script: bash -c 'echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; docker push tooxo/website-mainpage:mainpage'
    # Deploy Spotify2mp3 to GitHub
    -   provider: script
        script: bash -c "echo '"$GITHUB_KEY" | docker login docker.pkg.github.com --username "$GITHUB_USERNAME" --password-stdin; docker push docker.pkg.github.com/tooxo/website-mainpage/spotify2mp3'
    # Deploy Spotify2Mp3 to DockerHub
    -   provider: script
        script: bash -c 'echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; docker push tooxo/website-mainpage:spotify2mp3'