language: minimal
services:
    - docker

before_deploy:
    - docker build . -t docker.pkg.github.com/tooxo/website-mainpage/mainpage
    - docker build . -t tooxo/website-mainpage:mainpage
    - docker build SpotifyToMp3/ -t docker.pkg.github.com/tooxo/website-mainpage/spotifytomp3
    - docker build SpotifyToMp3/ -t tooxo/website-mainpage:spotifytomp3
    - docker build ArtistWordRanker/ -t docker.pkg.github.com/tooxo/website-mainpage/awr
    - docker build ArtistWordRanker/ -t tooxo/website-mainpage:awr


deploy:
    # Deploy MainPage to GitHub
    -   provider: script
        script: bash -c 'echo "$GITHUB_KEY" | docker login docker.pkg.github.com --username "$GITHUB_USERNAME" --password-stdin; docker push docker.pkg.github.com/tooxo/website-mainpage/mainpage'
    # Deploy MainPage to DockerHub
    -   provider: script
        script: bash -c 'echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; docker push tooxo/website-mainpage:mainpage'
    # Deploy Spotify2mp3 to GitHub
    -   provider: script
        script: bash -c 'echo "$GITHUB_KEY" | docker login docker.pkg.github.com --username "$GITHUB_USERNAME" --password-stdin; docker push docker.pkg.github.com/tooxo/website-mainpage/spotifytomp3'
    # Deploy Spotify2Mp3 to DockerHub
    -   provider: script
        script: bash -c 'echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; docker push tooxo/website-mainpage:spotifytomp3'
    # Deploy Spotify2mp3 to GitHub
    -   provider: script
        script: bash -c 'echo "$GITHUB_KEY" | docker login docker.pkg.github.com --username "$GITHUB_USERNAME" --password-stdin; docker push docker.pkg.github.com/tooxo/website-mainpage/awr'
    # Deploy Spotify2Mp3 to DockerHub
    -   provider: script
        script: bash -c 'echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; docker push tooxo/website-mainpage:awr'