version: '2'
services:
    web:
        build: .
        command: npm run start
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        ports:
            - "8002:8080"

