version: '2'
services:
    web:
        build: .
        command: npm run start
        volumes:
            - .:/usr/src/app/
            - /usr/src/app/node_modules
        #ports:
        #    - "8002:8080"
    web2:
        build:
            context: ./SpotifyToMp3
        command: /bin/sh -c "cd /usr/src/app/ && gunicorn --bind=0.0.0.0:8006 wsgi:app"
        volumes:
            - ./SpotifyToMp3:/usr/src/app/
        #ports:
        #    - "8006:8006"
        env_file:
          - ./SpotifyToMp3/vars.env
    awr:
        build:
          context: ./ArtistWordRanker
        command: /bin/sh -c "cd /usr/src/app && python server.py"
        volumes:
          - ./ArtistWordRanker:/usr/src/app/
        #ports:
        #    - "8888:8888"
        env_file:
          - ./ArtistWordRanker/.env